services:
  pipeline_training:
    build:
      context: .
      dockerfile: Dockerfile.pl
#    image: pl_test:latest
    working_dir: /pl
    command: |
      sh -c "
      $$VENV_PL/bin/aigear-task workflow --version logistic_regression --step fetch_data &&
      $$VENV_PL/bin/aigear-task workflow --version logistic_regression --step preprocessing &&
      $$VENV_PL/bin/aigear-task workflow --version logistic_regression --step training &&
      tail -f /dev/null
      "
    volumes:
      - .:/pl:rw

# docker compose -f docker-compose-pl.yml up -d
