services:
  pipeline-version:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /{project_name}
    ports:
      - 50001:50051
    command:  |
      sh -c "
      aigear-workflow --version {pipeline version} --step {Step path 1} &
      aigear-workflow --version {pipeline version} --step {Step path 2} & 
      tail -f /dev/null
      "
    volumes:
      - ./.config/gcloud:/root/.config/gcloud:r
      - .:/{project_name}:rw
    networks:
      - backend

networks:
  backend:
    external: true
