services:
  model_service:
    build:
      context: .
      dockerfile: Dockerfile.ms
#    image: ms_test:latest
    working_dir: /ms
    ports:
      - 50051:50051
    command: |
      sh -c "
      $$VENV_MS/bin/aigear-task grpc --version logistic_regression &&
      tail -f /dev/null
      "
    volumes:
      - .:/ms:rw

# docker compose -f docker-compose-ms.yml up -d
