services:
  pipeline_training:
    build:
      context: .
      dockerfile: Dockerfile.pl
#    image: pl_test:latest
    working_dir: /pl
    command: |
      sh -c "
      $$VENV_PL/bin/aigear-task workflow --version logistic_regression --module src.pipelines.logistic_regression.fetch_data.data_from_sklearn.fetch_data &&
      $$VENV_PL/bin/aigear-task workflow --version logistic_regression --module src.pipelines.logistic_regression.preprocessing.feature_processing.feature_processing &&
      $$VENV_PL/bin/aigear-task workflow --version logistic_regression --module src.pipelines.logistic_regression.training.train.train_model &&
      tail -f /dev/null
      "
    volumes:
      - .:/pl:rw

# docker compose -f docker-compose-pl.yml up -d
