apiVersion: apps/v1
kind: Deployment
metadata:
  name: aigear-sklearn-pipeline-logistic-regression-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aigear-sklearn-pipeline-logistic-regression-service
  template:
    metadata:
      labels:
        app: aigear-sklearn-pipeline-logistic-regression-service
    spec:
      containers:
      - name: aigear-sklearn-pipeline-logistic-regression-service
        image: asia-northeast1-docker.pkg.dev/ssc-ape-staging/test-sklearn-pipeline-images/test-sklearn-model-service:latest
        imagePullPolicy: Always
        command: ["/opt/venv/ms/bin/aigear-task", "grpc"]
        args:
          - "--version"
          - "logistic_regression"
        ports:
        - containerPort: 50051
---

apiVersion: v1
kind: Service
metadata:
  name: aigear-sklearn-pipeline-logistic-regression-service
spec:
  type: LoadBalancer
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app: aigear-sklearn-pipeline-logistic-regression-service
