
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aigear-sklearn-pipeline-logistic-regression-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aigear-sklearn-pipeline-logistic-regression-service
  template:
    metadata:
      labels:
        app: aigear-sklearn-pipeline-logistic-regression-service
    spec:
      containers:
      - name: aigear-sklearn-pipeline-logistic-regression-service
        image: asia-northeast1-docker.pkg.dev/{gcp project id}/test-sklearn-pipeline-images/aigear-sklearn-pipeline-service:latest
        imagePullPolicy: Never
        
        command: ["aigear-grpc"]
        args:
          - "--version"
          - "logistic_regression"
          - "--model_class_path"
          - "src.pipelines.logistic_regression.model_service.logistic_regression_service.ModelService"

        ports:
        - containerPort: 50051
        volumeMounts:
        - name: asset-volume
          mountPath: /ms/asset
      volumes:
      - name: asset-volume
        hostPath:
          path: /run/desktop/mnt/host/d/git_work/aigear_sklearn_pipeline/asset
          type: DirectoryOrCreate
---

apiVersion: v1
kind: Service
metadata:
  name: aigear-sklearn-pipeline-logistic-regression-service
spec:
  type: LoadBalancer
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app: aigear-sklearn-pipeline-logistic-regression-service
