# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-09-24T08:18:38+00:00

from __future__ import annotations

from pydantic import BaseModel


class Bucket(BaseModel):
    on: bool
    bucket_name: str
    bucket_name_for_release: str


class CloudBuild(BaseModel):
    on: bool
    trigger_name: str
    description: str
    repository: str
    repo_owner: str
    repo_name: str
    branch_pattern: str
    build_config: str
    substitutions: str


class CloudFunction(BaseModel):
    on: bool
    function_name: str


class Iam(BaseModel):
    on: bool
    account_name: str


class PubSub(BaseModel):
    on: bool
    topic_name: str


class Artifacts(BaseModel):
    on: bool
    repository_name: str


class Gcp(BaseModel):
    gcp_project_id: str
    location: str
    bucket: Bucket
    cloud_build: CloudBuild
    cloud_function: CloudFunction
    iam: Iam
    pub_sub: PubSub
    artifacts: Artifacts
    logging: bool


class Slack(BaseModel):
    on: bool
    webhook_url: str


class Config(BaseModel):
    gcp: Gcp
    slack: Slack
