# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-08-15T01:17:48+00:00

from __future__ import annotations

from pydantic import BaseModel


class Bucket(BaseModel):
    bucket_name: str
    bucket_name_for_release: str
    location: str
    on: bool


class CloudBuild(BaseModel):
    trigger_name: str
    description: str
    repository: str
    repo_owner: str
    repo_name: str
    branch_pattern: str
    build_config: str
    region: str
    substitutions: str


class CloudFunction(BaseModel):
    function_name: str
    region: str


class Iam(BaseModel):
    account_name: str


class PubSub(BaseModel):
    topic_name: str
    sub_name: str


class Gcp(BaseModel):
    gcp_project_id: str
    bucket: Bucket
    cloud_build: CloudBuild
    cloud_function: CloudFunction
    iam: Iam
    pub_sub: PubSub
    logging: bool


class Slack(BaseModel):
    on: bool
    webhook_url: str


class Config(BaseModel):
    gcp: Gcp
    slack: Slack
