# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-01-20T08:32:59+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, model_validator


class Bucket(BaseModel):
    on: bool
    bucket_name: str
    bucket_name_for_release: str


class CloudBuild(BaseModel):
    on: bool
    trigger_name: str
    description: str
    repo_owner: str
    repo_name: str
    event: str = "push"  # push | tag | pull
    branch_pattern: Optional[str] = None
    tag_pattern: Optional[str] = None


class Kms(BaseModel):
    on: bool
    keyring_name: str
    key_name: str


class PreVmImage(BaseModel):
    on: bool


class CloudFunction(BaseModel):
    on: bool
    function_name: str


class Iam(BaseModel):
    on: bool
    account_name: str


class PubSub(BaseModel):
    on: bool
    topic_name: str


class Artifacts(BaseModel):
    on: bool
    repository_name: str
    ms_image_name: Optional[str] = None
    pl_image_name: Optional[str] = None
    image_tag: Optional[str] = "latest"


class Kubernetes(BaseModel):
    on: bool
    cluster_name: str
    num_nodes: int
    min_nodes: int
    max_nodes: int


class Firestore(BaseModel):
    on: bool
    # Optional Pipeline V2 addition (docs/pipeline-asset-lifecycle-management-v2.md
    # section 2.1). Absent by default so existing env.json files keep validating
    # unchanged; environments that opt into V2 must set it explicitly.
    database_id: Optional[str] = None


class RegistryV2(BaseModel):
    """Optional Pipeline V2 identity inputs (spec section 2.1).

    All fields are optional and additive: they are only required by callers
    that compute a V2 ``environment_fingerprint`` or ``registry_binding``; a
    project that never touches Pipeline V2 does not need this section at all.
    """

    enabled: bool = False
    environment_id: Optional[str] = None
    gcp_project_number: Optional[str] = None
    asset_bucket_location: Optional[str] = None
    kms_trust_domain: Optional[str] = None
    security_journal_bucket: Optional[str] = None
    manifest_integrity_key_version: Optional[str] = None
    blob_location_key_version: Optional[str] = None
    occurrence_finalization_key_version: Optional[str] = None
    completion_topic: Optional[str] = None
    completion_subscription: Optional[str] = None
    completion_publisher_service_account: Optional[str] = None
    completion_oidc_audience: Optional[str] = None

    @model_validator(mode="after")
    def validate_enabled_production_config(self):
        if not self.enabled:
            return self
        required = (
            "environment_id",
            "gcp_project_number",
            "asset_bucket_location",
            "kms_trust_domain",
            "security_journal_bucket",
            "manifest_integrity_key_version",
            "blob_location_key_version",
            "occurrence_finalization_key_version",
            "completion_topic",
            "completion_subscription",
            "completion_publisher_service_account",
            "completion_oidc_audience",
        )
        missing = [name for name in required if not getattr(self, name)]
        if missing:
            raise ValueError(
                "registry_v2.enabled=true requires " + ", ".join(missing)
            )
        for name in (
            "manifest_integrity_key_version",
            "blob_location_key_version",
            "occurrence_finalization_key_version",
        ):
            if "/cryptoKeyVersions/" not in getattr(self, name):
                raise ValueError(f"registry_v2.{name} must pin a full CryptoKeyVersion resource")
        key_versions = {
            self.manifest_integrity_key_version,
            self.blob_location_key_version,
            self.occurrence_finalization_key_version,
        }
        if len(key_versions) != 3:
            raise ValueError("registry_v2 attestation key versions must be distinct")
        if not self.gcp_project_number.isdigit():
            raise ValueError("registry_v2.gcp_project_number must contain digits only")
        if not self.completion_publisher_service_account.endswith(".gserviceaccount.com"):
            raise ValueError(
                "registry_v2.completion_publisher_service_account must be a service account email"
            )
        return self


class Gcp(BaseModel):
    gcp_project_id: str
    location: str
    bucket: Bucket
    cloud_build: CloudBuild
    kms: Kms
    pre_vm_image: PreVmImage
    cloud_function: CloudFunction
    iam: Iam
    pub_sub: PubSub
    artifacts: Artifacts
    kubernetes: Kubernetes
    firestore: Firestore
    logging: bool
    registry_v2: Optional[RegistryV2] = None

    @model_validator(mode="after")
    def validate_registry_v2_dependencies(self):
        if self.registry_v2 is None or not self.registry_v2.enabled:
            return self
        missing_or_disabled = []
        if not self.firestore.on or not self.firestore.database_id:
            missing_or_disabled.append("firestore.on/database_id")
        if not self.bucket.on or not self.bucket.bucket_name:
            missing_or_disabled.append("bucket.on/bucket_name")
        if not self.kms.on:
            missing_or_disabled.append("kms.on")
        if not self.pub_sub.on:
            missing_or_disabled.append("pub_sub.on")
        if missing_or_disabled:
            raise ValueError(
                "registry_v2.enabled=true requires " + ", ".join(missing_or_disabled)
            )
        return self


class Config(BaseModel):
    gcp: Gcp
