# generated by datamodel-codegen:
#   filename:  env.json
#   timestamp: 2026-04-15T02:17:22+00:00

from __future__ import annotations
from pydantic import BaseModel


class Bucket(BaseModel):
    on: bool
    bucket_name: str
    bucket_name_for_release: str


class CloudBuild(BaseModel):
    on: bool
    trigger_name: str
    description: str
    repo_owner: str
    repo_name: str
    event: str
    branch_pattern: str
    tag_pattern: str


class Kms(BaseModel):
    on: bool
    keyring_name: str
    key_name: str


class PreVmImage(BaseModel):
    on: bool


class CloudFunction(BaseModel):
    on: bool
    function_name: str


class Iam(BaseModel):
    on: bool
    account_name: str


class PubSub(BaseModel):
    on: bool
    topic_name: str


class Artifacts(BaseModel):
    on: bool
    repository_name: str
    ms_image_name: str
    pl_image_name: str
    image_tag: str


class Kubernetes(BaseModel):
    on: bool
    cluster_name: str
    num_nodes: int
    min_nodes: int
    max_nodes: int


class Gcp(BaseModel):
    gcp_project_id: str
    location: str
    bucket: Bucket
    cloud_build: CloudBuild
    kms: Kms
    pre_vm_image: PreVmImage
    cloud_function: CloudFunction
    iam: Iam
    pub_sub: PubSub
    artifacts: Artifacts
    kubernetes: Kubernetes
    logging: bool


class Slack(BaseModel):
    on: bool
    webhook_url: str


class Aigear(BaseModel):
    gcp: Gcp
    slack: Slack


class Scheduler(BaseModel):
    name: str
    schedule: str
    time_zone: str


class Parameters(BaseModel):
    data_file_name: str


class Resources(BaseModel):
    vm_name: str
    disk_size_gb: str
    spec: str
    gpu: bool


class FetchData(BaseModel):
    parameters: Parameters
    resources: Resources
    pipeline_step: str


class Parameters1(BaseModel):
    feature_file_name: str
    scaler_model: str


class Preprocessing(BaseModel):
    parameters: Parameters1
    resources: Resources
    pipeline_step: str


class Parameters2(BaseModel):
    logistic_model: str


class Training(BaseModel):
    parameters: Parameters2
    resources: Resources
    pipeline_step: str


class KeepAlive(BaseModel):
    time: int
    timeout: int


class MultiProcessing(BaseModel):
    on: bool
    process_count: int
    thread_count: int
    disable_omp: bool


class Sentry(BaseModel):
    on: bool
    dsn: str
    traces_sample_rate: float


class Grpc(BaseModel):
    keep_alive: KeepAlive
    service_host: str
    port: str
    multi_processing: MultiProcessing
    sentry: Sentry


class ModelService(BaseModel):
    release: bool
    venv_ms: str
    grpc: Grpc
    resources: Resources
    model_class_path: str


class LogisticRegression(BaseModel):
    venv_pl: str
    scheduler: Scheduler
    fetch_data: FetchData
    preprocessing: Preprocessing
    training: Training
    model_service: ModelService


class Pipelines(BaseModel):
    logistic_regression: LogisticRegression


class EnvSchema(BaseModel):
    project_name: str
    environment: str
    aigear: Aigear
    pipelines: Pipelines
